# Jika Anda punya akun Ko-fi atau Buy Me A Coffee, cukup tulis username-nya
ko_fi: ilramdhan_

# Untuk platform lokal seperti Saweria atau Trakteer, gunakan opsi 'custom' beserta link penuhnya
custom: ['https://saweria.co/ilramadhan']
